// instalar extension sc llamada api rest


//Generated repo from id
curl http://localhost:3000/api/creaRepositorio

###
//add new  item
curl -X POST http://localhost:3000/api/item/c344b814-e61f-4195-985b-d4ed28beb5bb -H "Content-Type: application/json" -d '{"name": "Item 1", "description": "This is item 1"}'

###

// get all items
curl http://localhost:3000/api/items/c344b814-e61f-4195-985b-d4ed28beb5bb
###

//get all one item 
curl http://localhost:3000/api/item/c344b814-e61f-4195-985b-d4ed28beb5bb/06684e07-b9c4-4c5e-8037-22a2ba43185f
###

// find and update item 
curl -X PUT http://localhost:3000/api/item/c344b814-e61f-4195-985b-d4ed28beb5bb/06684e07-b9c4-4c5e-8037-22a2ba43185f -H "Content-Type: application/json" -d '{"name": "update Item 1"}'
###

// find and delete one item
curl -X DELETE http://localhost:3000/api/item/c344b814-e61f-4195-985b-d4ed28beb5bb/c9913668-3113-45a6-8a37-9bc948d7b4a3

